name: Your name here
description: Your description here
author: Your name or organization here
inputs:
  myInput:
    description: input description here
    default: default value if applicable
    required: false
runs:
  using: node12
  main: dist/index.js
